feat(app): creating navigation and header
Lomray-Software/microservices-dashboard pull request #2
Opened 2022-05-16 15:40 UTC by olegatorlelik

2022-05-16 16:19 UTC, MatthewPattell requested changes

2022-05-16 16:19 UTC, MatthewPattell commented on src/common/components/header/index.tsx
> +import SideMenu from '../side-menu/index';
'@components/side-menu';

side-menu не связан с header

2022-05-16 16:19 UTC, MatthewPattell commented on src/common/components/layout/index.tsx
> +import SideMenu from '../side-menu/index';
'@components/side-menu';

side-menu не связан с layout

2022-05-16 16:19 UTC, MatthewPattell commented on src/common/components/layout/index.tsx
> +        {hasFooter && <Footer />}
я бы все же футер внутри main не держал бы

2022-05-16 16:19 UTC, MatthewPattell commented on src/common/components/side-menu/index.tsx
> + */
эта штука рядом с const SideMenu:

2022-05-16 16:19 UTC, MatthewPattell commented on src/common/components/side-menu/index.tsx
> +        {!isToggle ? APP_SHORT_NAME : 'D'}
)) буква D это первая буква из APP_SHORT_NAME

2022-05-16 16:19 UTC, MatthewPattell commented on src/common/components/header/index.tsx
> +        D
APP_SHORT_NAME первая буква

2022-05-16 16:19 UTC, MatthewPattell commented on src/common/modals/user/index.tsx
> +import { mdiCogSync, mdiExitRun } from '@mdi/js';
это не модалка и выносить это не стоило. Это просто относительный компонент для header

2022-05-16 16:19 UTC, MatthewPattell commented on src/constants/menu.ts
> +    hasFlashingPoint?: boolean;
hasFlashingPoint копипаст подьехал

2022-05-16 16:19 UTC, MatthewPattell commented on src/common/helpers/use-toggle.ts
> +  return [isValue, toggle];
useCallback + prevValue + useMemo

2022-05-17 07:42 UTC, MatthewPattell requested changes

2022-05-17 07:42 UTC, MatthewPattell commented on src/common/components/header/index.tsx
> +import SideMenu from '@components/side-menu/index';
'@components/side-menu/index' => '@components/side-menu';

2022-05-17 07:42 UTC, MatthewPattell commented on src/common/components/layout/index.tsx
> +import SideMenu from '@components/side-menu/index';
'@components/side-menu/index' => '@components/side-menu';

2022-05-17 07:42 UTC, MatthewPattell commented on src/common/components/header/user/popup/index.tsx
> +          <Link to="/settings" className={combineCss(styles.item, styles.link)}>
<Link to={ROUTES.SETTINGS}

2022-05-17 07:42 UTC, MatthewPattell commented on src/common/components/layout/index.tsx
> +  const [isToggle, setIsToggle] = useToggle(false);
не нравится мне это. в layout нужно избегать стэйтов и пр.

2022-05-17 07:42 UTC, MatthewPattell commented on src/common/components/layout/index.tsx
> +      </main>
don't put your site's header/menu/footer (repeated content) in your <main>.

нашел где-то на просторах интернета.

2022-05-17 07:42 UTC, MatthewPattell commented on src/common/components/side-menu/index.tsx
> +      <Link to="/" className={styles.title}>
to={ROUTES.HOME}

2022-05-17 07:42 UTC, MatthewPattell commented on src/common/components/header/index.tsx
> +  const [isOpenNavigation, setIsOpenNavigation] = useToggle(false);
написать - написал. Но вот четко ли? Нет. У тебя 2 стэйта с которыми ты проп дриллингом занимаешься

2022-05-17 13:27 UTC, MatthewPattell requested changes

2022-05-17 13:27 UTC, MatthewPattell commented on src/store/modules/app-store/index.ts
> +  public isNavigation = false;
hasNavigation 
за что отвечает этот флаг? За фулл сайд бар или за шорт? Если да, то логичнее было бы аля hasFullSidebar и т.п.

2022-05-17 13:27 UTC, MatthewPattell commented on src/store/modules/user/index.ts
> +  public isOpenPopup = false;
неудачное место для этого. Что за попап? Для пунктов меню когда на юзера жмем? Тогда это вообще компонент должен быть который эту логику в себе инкапсулирует, стор отдельный и т.д. Точно не здесь

2022-05-17 13:55 UTC, olegatorlelik commented on src/store/modules/user/index.ts
> +  public isOpenPopup = false;
Я думал оно типо к юзеру относиться, компонент узера и попам к нему с информацией о нем

2022-05-17 14:55 UTC, MatthewPattell requested changes

2022-05-17 14:55 UTC, MatthewPattell commented on src/store/modules/app-store/index.ts
> +  public toggleMenuNavigation(): void {
toggleSidebar

2022-05-17 15:06 UTC, MatthewPattell approved these changes

2022-05-17 15:06 UTC, merged