feat(user-page): creating
Lomray-Software/microservices-dashboard pull request #3
Opened 2022-06-01 16:40 UTC by olegatorlelik

2022-06-01 20:52 UTC, MatthewPattell requested changes

2022-06-01 20:52 UTC, MatthewPattell commented on src/assets/locales/en/users-page.json
> +  "username": "User name",
Это не разделяется. Username

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/forms/field/index.tsx
> +import Input from '../input';
везде импорт через алиас а здесь относительный, приведи к одному виду

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/forms/field/index.tsx
> +interface IFormikField {
IField - по названию компонента

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/forms/field/index.tsx
> +const Field: FC<InputHTMLAttributes<HTMLInputElement> & IFormikField> = ({
type Props = InputHTMLAttributes<HTMLInputElement> & IField;

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/forms/field/index.tsx
> +  isColumn?: boolean;
isInline

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/forms/input/index.tsx
> +const Input: FC<InputHTMLAttributes<HTMLInputElement>> = ({ ...props }) => (
type Props = InputHTMLAttributes<HTMLInputElement>

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/forms/label/index.tsx
> +const Label: FC<LabelHTMLAttributes<HTMLLabelElement>> = ({ children, ...props }) => (
type Props =

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/header/user/popup/index.tsx
> +  id?: string;
userId

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/layout/breadcrumbs/index.tsx
> +const Breadcrumbs: FC<RouteComponentProps> = (props) => {
({ history, location: { pathname } })

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/layout/breadcrumbs/index.tsx
> +        Home
t()

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +import DefaultFilter from '@components/table/default-filter';
импорт

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +import Select from '@components/table/select';
импорт

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +  setCurrentPage: (page: number) => void;
setPage

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +const START_PAGE = 1;
лишняя.

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +  const defaultColumn = React.useMemo(
useMemo, где деструктуризация?

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +                          to={makeUrl([makeUrl([ROUTES.USERS, String(row.original.id)])])}>
таблица универсальная должна быть, какое ROUTES.USERS?

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/helpers/set-errors-form.ts
> +  result: IValidationErrors<IEditProfileState> | true,
IEditProfileState - какое. Это универсальный компонент! generic здесь должен быть

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/helpers/set-errors-form.ts
> +  result: IValidationErrors<IEditProfileState> | true,
это тип, какое true? boolean

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/helpers/set-errors-form.ts
> + * set errors for fields and main error
Set errors ...

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/helpers/set-errors-form.ts
> +import type { IEditProfileState } from '@store/modules/pages/user/efit-profile';
remove

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/login/index.tsx
> +import Field from '@components/forms/field/index';
import Field from '@components/forms/field';

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/change-password/index.tsx
> +import Field from '@components/forms/field/index';
import Field from '@components/forms/field';

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/change-password/index.tsx
> +          {fields.map((item) => (
{fields.map((name) => (

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.stores.ts
> +  userEditProfile: EditProfileStore,
userEdit: UserEditStore

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.tsx
> +import type { IEditProfileState } from '@store/modules/pages/user/efit-profile';
efit-profile )))

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/edit-profile/validation-schema.ts
> +    username: string().trim().min(2, tooShortError),
required

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/edit-profile/validation-schema.ts
> +    firstName: string().trim().required(requiredError).min(2, tooShortError).max(70, tooLongError),
required

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/edit-profile/validation-schema.ts
> +    birthDay: string().trim().min(2, tooShortError),
с такой валидацией они все обязательные?

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +import CardUser from '@pages/user/card-user';
импорт

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +  const child = useMemo(() => {
activeTab

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +          ))}
мб отдельный компонент? У нас еще будут страницы с табами

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/overview/index.tsx
> +  console.log(user?.username);
????

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/user/overview/index.tsx
> +const Overview: FC<IOverview> = ({ user }) => {
Тоже мб отдельный компонент? У нас будут еще сущности где нужно будет вывести поля

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/users/index.tsx
> +import stores from '@pages/users/index.stores';
импорт

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/users/index.tsx
> +import type { StoreProps } from '@pages/users/index.stores';
импорт

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/users/index.tsx
> -      {
зачем ты убрал вывод id?

2022-06-01 20:52 UTC, MatthewPattell commented on src/pages/users/index.tsx
> +        disableSortBy: true,
почему вырубил сортировку по этому полю?

2022-06-01 20:52 UTC, MatthewPattell commented on src/store/modules/pages/user/efit-profile.ts
> +class EditProfileStore implements IUi {
EditUserStore

2022-06-01 20:52 UTC, MatthewPattell commented on src/common/helpers/set-errors-form.ts
> +import type { FormikErrors } from 'formik';
все что здесь положить сюда:

src/common/helpers/format-validation-errors.ts

файл переименовать в handle-validation-errors.ts

2022-06-01 20:52 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +class EditProfileStore implements IUi {
ChangePasswordStore implements IDomain

2022-06-01 20:52 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +}
не то

2022-06-01 20:52 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +import { action, makeObservable, observable } from 'mobx';
я так понял это копипасто который поменяется после реализации

2022-06-01 20:52 UTC, MatthewPattell commented on src/store/modules/pages/user/efit-profile.ts
> +import { action, makeObservable, observable } from 'mobx';
src/store/modules/pages/user/efit-profile.ts => src/store/modules/pages/user/edit-profile.ts

2022-06-01 20:52 UTC, MatthewPattell commented on src/store/modules/pages/user/efit-profile.ts
> +      .user as IUser;
as IUser зачем?

2022-06-01 20:52 UTC, MatthewPattell commented on src/store/modules/pages/users/index.ts
> +    await this.getUsers();
return this.getUsers();

2022-06-01 20:52 UTC, MatthewPattell commented on src/store/modules/pages/users/index.ts
> +    await this.getUsers();
return

2022-06-02 07:54 UTC, olegatorlelik commented on src/common/components/forms/input/index.tsx
> +const Input: FC<InputHTMLAttributes<HTMLInputElement>> = ({ ...props }) => (
Он принимает дженерик поэтому наверное так type TProp = InputHTMLAttributes<HTMLInputElement>;

2022-06-02 08:21 UTC, olegatorlelik commented on src/common/helpers/set-errors-form.ts
> +  result: IValidationErrors<IEditProfileState> | true,
Тут косячок)))

2022-06-02 09:26 UTC, olegatorlelik commented on src/pages/user/overview/index.tsx
> +  console.log(user?.username);
упс)

2022-06-02 09:28 UTC, olegatorlelik commented on src/pages/users/index.tsx
> -      {
а зачем оно?

2022-06-02 09:28 UTC, olegatorlelik commented on src/pages/users/index.tsx
> +        disableSortBy: true,
Тестил, забыл убрать, мискузи

2022-06-02 09:31 UTC, olegatorlelik commented on src/store/modules/pages/user/change-password.ts
> +class EditProfileStore implements IUi {
Это я еще просто не доделал, точнее на начинал а так заготовочку подготовил, хотел убедиться в том что я делаю правильно

2022-06-02 09:31 UTC, olegatorlelik commented on src/store/modules/pages/user/change-password.ts
> +}
Это я еще просто не доделал, точнее на начинал а так заготовочку подготовил, хотел убедиться в том что я делаю правильно

2022-06-02 09:32 UTC, olegatorlelik commented on src/store/modules/pages/user/efit-profile.ts
> +      .user as IUser;
Потому что user может быть налом, но в данном случаи мы знаем что юзер будет, если я правильно понимаю то в этом случаи это применимо

2022-06-02 09:33 UTC, olegatorlelik commented on src/store/modules/pages/user/change-password.ts
> +import { action, makeObservable, observable } from 'mobx';
Конечно

2022-06-02 09:45 UTC, MatthewPattell commented on src/pages/users/index.tsx
> -      {
не придумывай. Раз он был - значит нужно. Ты с админками никогда не работал. Это поле одно из ключевых полей

2022-06-02 12:43 UTC, MatthewPattell commented on src/store/modules/pages/user/efit-profile.ts
> +      .user as IUser;
Тогда лучше себя вот так обезопасить:
```
const { firstName, lastName, middleName, phone, profile, username } = this.userStore.user || {};
```

2022-06-03 14:51 UTC, MatthewPattell requested changes

2022-06-03 14:51 UTC, MatthewPattell commented on src/assets/locales/ru/user-page.json
> +  "changePassword": "Change password",
???

2022-06-03 14:51 UTC, MatthewPattell commented on src/assets/locales/ru/users-page.json
> +  "deletedAt": "Удаленно At",
без At

2022-06-03 14:51 UTC, MatthewPattell commented on src/assets/styles/global.scss
> +//this selector need for position breadcrumbs
// This selector...

2022-06-03 14:51 UTC, MatthewPattell commented on src/common/components/breadcrumbs/breadcrumb-item.tsx
> +import styles from '@components/breadcrumbs/styles.module.scss';
импорт

2022-06-03 14:51 UTC, MatthewPattell commented on src/common/components/breadcrumbs/index.tsx
> +import BreadcrumbItem from '@components/breadcrumbs/breadcrumb-item';
импорты

2022-06-03 14:51 UTC, MatthewPattell commented on src/common/components/fields/index.tsx
> +const Fields: FC<IFields> = ({ data }) => (
EntityFields

2022-06-03 14:51 UTC, MatthewPattell commented on src/common/components/header/user/index.tsx
> +import type { StoreProps } from '@components/header/user/index.stores';
импорт

2022-06-03 14:51 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +    (countUser: number) => {
pageSize: number

2022-06-03 14:51 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +    (selectedPage: number) => {
page: number

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/login/index.tsx
> +                <ErrorMessage>{error}</ErrorMessage>
зачем внутри кнопки??

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/change-password/index.tsx
> +            <ErrorMessage>{error}</ErrorMessage>
внути кнопки должен быть только тайтл

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/change-password/validation-schema.ts
> +const notMatch = i18n.t('forms:vNotMatch');
нет, выносить так нельзя. Внутрь ложи, в этом и фишка. Короче константы излишни

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.tsx
> +import Field from '@components/forms/field/index';
ты запаришь с этими импортами.

`import Field from '@components/forms/field';`

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/edit-profile/validation-schema.ts
> +const tooLongError = i18n.t('forms:vTooLong');
нет, на константы не выносить

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/edit-profile/validation-schema.ts
> +    firstName: string().trim().required(requiredError).min(2, tooShortError).max(70, tooLongError),
required первым всегда ставим

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/edit-profile/validation-schema.ts
> +    username: string().trim().required(requiredError).min(2, tooShortError),
.max(70, tooLongError),

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/edit-profile/validation-schema.ts
> +const tooLongError = i18n.t('forms:vTooLong');
нужно вообще подумать как по дефолту задать транслэйшн для yup валидации

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +        <Breadcrumbs.Item to={ROUTES.HOME} title={t('menu:home')} />
по дефолту это должно быть внутри (для home)

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +        <Tabs tabs={tabs} activeTab={activeTab} setActiveTab={setActiveTab} />
короче. Табы реализованы не так. Пойдем путем по проще, вот это просто возьми и все:
https://github.com/reactjs/react-tabs

можно оберку создать чтобы стилизануть и все

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/users/index.tsx
> +        <Breadcrumbs.Item to={ROUTES.HOME} title={t('menu:home')} />
дефотная херня

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/users/index.tsx
> +        link={ROUTES.USERS}
не, сделаем аля:

onRoute={() => makeUrl(...)}

строим ссылки на стороне старницы а не таблицы, таблица не знает как их строить правильно

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/endpoints/index.ts
> +      changePassword: this.createHandler<IChangePasswordState, IView<IUser>>(
IChangePassword

без State т.к. это не state, забудь про редакс))

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +import UserPageStore from '@store/modules/pages/user/index';
опять этот index на конце....

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +    ]);
зачем тебе Promise.all для 1 запроса??

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/edit-profile.ts
> +import UserPageStore from '@store/modules/pages/user/index';
index

2022-06-03 14:51 UTC, MatthewPattell commented on src/common/components/tabs/index.tsx
> +const Tabs: FC<ITabs> = ({ tabs, activeTab, setActiveTab }) => (
уберем и побключим либу, реализация не та, с либой проще и быстрее

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.tsx
> +          <SubmitButton className={styles.button} hasLoader>
нет общей ошибки

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.tsx
> +              <span className={styles.description}>{t(`users-page:${fieldName}`)}</span>
эта штука под вопросом

2022-06-03 14:51 UTC, MatthewPattell commented on src/pages/user/change-password/index.tsx
> +              <span className={styles.description}>{t(name)}</span>
эта штука под вопросом

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +        reEnterNewPassword: 'reEnterNewPassword',
это нужно для сопоставления имени поля на стороне фронта и бэка.
Слева имя поля на стороне фронта, справа на стороне бэка, в том случае если отличаются.

Убери это пока что

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/edit-profile.ts
> +          lastName: 'lastName',
я про это уже объяснил, убери это бесполезно

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +      return formatValidationError<IChangePasswordState, Record<any, any>>(changePasswordError, {
Record<any, any> не то

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/index.ts
> +  public async updatePassword(fields: IChangePasswordState): Promise<IBaseException | undefined> {
зачем это здесь? У тебя ж отдельный стор по изменению пароля

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/edit-profile.ts
> +      this.userStore.updateProfile({ birthDay }),
shouldShowErrors: false

2022-06-03 14:51 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +    ]);
не забудь shouldShowErrors: false

2022-06-03 14:52 UTC, MatthewPattell commented on src/assets/locales/ru/user-page.json
> +  "changePassword": "Change password",
русский

2022-06-06 15:45 UTC, olegatorlelik commented
this version is not final since all fields are not added and there is no processing of successful form submission, this needs to be discussed

2022-06-06 16:29 UTC, MatthewPattell requested changes

2022-06-06 16:29 UTC, MatthewPattell commented on src/common/components/entity-fields/index.tsx
> +interface IFields {
нэйминг интерфейса

2022-06-06 16:29 UTC, MatthewPattell commented on src/common/components/forms/submit-button/index.tsx
> +  error: string | null;
formError

я так не хочу сюда это впихивать, потому что ошибка не относится к кнопке. Но придумать как бы оптимизировать не могу. Я конечно могу спросить почему ошибка не может позиционироваться отдельно....

2022-06-06 16:29 UTC, MatthewPattell commented on src/pages/login/validation-schema.ts
>        .trim()
в этом случае trim будет выше) сначала работает trim потом required потом остальные валидаторы

2022-06-06 16:29 UTC, MatthewPattell commented on src/pages/login/validation-schema.ts
>        .min(2, i18n.t('forms:vTooShort'))
тоже самое

2022-06-06 16:29 UTC, MatthewPattell commented on src/pages/user/change-password/validation-schema.ts
> +    newPassword: string().required(i18n.t('forms:vRequired')).trim(),
trim, required

2022-06-06 16:29 UTC, MatthewPattell commented on src/pages/user/edit-profile/validation-schema.ts
> +      .trim()
ну ты понял

2022-06-06 16:29 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +          title={user?.username ?? `${String(user?.firstName)} ${String(user?.lastName)}`}
заигнорил это. User.getName(user)

2022-06-06 16:29 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +}
лишнее

2022-06-06 16:29 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +  );
Я тут подумал, это тоже не нужно.

2022-06-06 16:29 UTC, MatthewPattell commented on src/store/modules/pages/user/change-password.ts
> +  private userStore: ClassReturnType<typeof UserPageStore>;
тоже что и для edit profile

2022-06-06 16:29 UTC, MatthewPattell commented on src/store/modules/pages/user/edit-profile.ts
> +class EditUserStore implements IUi {
IDomain

2022-06-06 16:29 UTC, MatthewPattell commented on src/store/modules/pages/user/edit-profile.ts
> +  private userStore: ClassReturnType<typeof UserPageStore>;
userPageStore давай имя дадим чтобы не попутать с userStore который в modules/user

2022-06-06 16:29 UTC, MatthewPattell commented on src/store/modules/pages/user/edit-profile.ts
> +import UserPageStore from '@store/modules/pages/user';
импорт

2022-06-06 16:29 UTC, MatthewPattell commented on src/typings/react-tabs.d.ts
> +declare module 'react-tabs';
зачем это если ты поставил пакет типов для этой либы?

2022-06-06 16:29 UTC, MatthewPattell commented on src/common/helpers/make-route.ts
> +const makeRoute =
jsdoc когда уже будем писать?

2022-06-08 16:33 UTC, MatthewPattell requested changes
src/assets/images/defaults/user.jpg

2022-06-08 16:33 UTC, MatthewPattell commented on package.json
> +    "@types/lodash.isempty": "^4.4.7",
devDependencies ну

2022-06-08 16:33 UTC, MatthewPattell commented on src/assets/locales/en/translation.json
> +  "success": "Успешно !"
Success

2022-06-08 16:33 UTC, MatthewPattell commented on src/assets/locales/en/users-page.json
> +  "titleNotification": "Form submission information",
Information

2022-06-08 16:33 UTC, MatthewPattell commented on src/assets/locales/ru/translation.json
> +  "success": "Success !"
"Успешно"

2022-06-08 16:33 UTC, MatthewPattell commented on src/assets/locales/ru/users-page.json
> +  "titleNotification": "Информация о подаче формы",
Информация о подаче формы? Ты серьезно???

"titleNotification": "Информация",

2022-06-08 16:33 UTC, MatthewPattell commented on src/assets/locales/ru/users-page.json
> +  "titleNotification": "Информация о подаче формы",
это в translation

2022-06-08 16:33 UTC, MatthewPattell commented on src/assets/locales/ru/users-page.json
> +  "messageNotification": "Изменения сохранены"
это в translation

2022-06-08 16:33 UTC, MatthewPattell commented on src/assets/locales/en/users-page.json
> +  "titleNotification": "Form submission information",
это в translation

2022-06-08 16:33 UTC, MatthewPattell commented on src/assets/locales/en/users-page.json
> +  "messageNotification": "Changes saved"
это в translation

2022-06-08 16:33 UTC, MatthewPattell commented on src/common/components/table/index.tsx
> +  const styleColumn = {
не обязательно создавать для этого отдельную константу

2022-06-08 16:33 UTC, MatthewPattell commented on src/common/helpers/make-route.ts
> + *
что это за пустая строка?

2022-06-08 16:33 UTC, MatthewPattell commented on src/common/components/forms/submit-button/index.tsx
> +      className={combineCss(String(props.className))}
что это?

2022-06-08 16:33 UTC, MatthewPattell commented on src/common/helpers/extend-yup-validation.ts
> +function ExtendYupValidation(): void {
а где вызов этого происходит?

2022-06-08 16:33 UTC, MatthewPattell commented on src/pages/user/data.ts
> +] as const;
новая идея:
```
const userFields = [
 { name: 'username' },
...
 { name: 'birthDay', type: 'date' },
];

const profileFields = [];
```

Это позволит избежать перечислений много где, плюс избавить внекоторых местах от конструкций вида:
```
field === 'birthDay'
```
что позволит все сделать более универсальным

2022-06-08 16:33 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.tsx
> +              type={fieldName === 'birthDay' ? 'date' : 'text'}
этого можно избежать, читай комент выше

2022-06-08 16:33 UTC, MatthewPattell commented on src/pages/user/overview/index.tsx
> +    value: field === 'birthDay' ? user?.profile?.birthDay : user?.[field],
можно избежать читай комент выше

2022-06-08 16:33 UTC, MatthewPattell commented on src/store/modules/pages/user/edit-profile.ts
> +    const profileField = pick(fields, ['birthDay']);
этих перечислений можно избежать, читай комент выше

2022-06-09 06:24 UTC, olegatorlelik commented on src/common/components/forms/submit-button/index.tsx
> +      className={combineCss(String(props.className))}
Это я фигню одну тестил так забыл убрать

2022-06-09 07:18 UTC, MatthewPattell commented on src/common/components/forms/submit-button/index.tsx
> +      className={combineCss(String(props.className))}
Фигово.

2022-06-09 19:57 UTC, MatthewPattell requested changes

2022-06-09 19:57 UTC, MatthewPattell commented on src/assets/locales/en/translation.json
> +  "success": "Success !",
"success": "Success",

2022-06-09 19:57 UTC, MatthewPattell commented on src/assets/locales/ru/translation.json
> +  "success": "Успешно !",
"success": "Успешно",

2022-06-09 19:57 UTC, MatthewPattell commented on src/common/components/entity-fields/index.tsx
> +      <div key={String(label)} className={styles.columnInfo}>
String(label) зачем если label и так string

2022-06-09 19:57 UTC, MatthewPattell commented on src/interfaces/select-options.ts
> +export interface ISelectOptions {
не обязательно отдельно было выносить, можно там же по месту селекта

2022-06-09 19:57 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.tsx
> +          {(profileFields as unknown as IProfileFields[]).map(({ name, type, options }) =>
нет

2022-06-09 19:57 UTC, MatthewPattell commented on src/pages/user/overview/index.tsx
> +
не нравится мне это. По сути этот компонент копипастить прийдется. Его же можно сделать универсальным

2022-06-09 20:14 UTC, MatthewPattell commented on src/pages/user/overview/index.tsx
> +
по факту если ты ключи переводов будешь в месте определения полей полностью писать, то этот компонент можно сделать универсальным
```
interface IOverview {
  entity: Record<string, any> | null;
  fields: { name: string; } // вообще как раз здесь можно было бы создать отдельный интерфейс для описания и присобачивать его в месте определения полей
  title: string;
}

const Overview: FC<IOverview> = ({ fields, entity, title }) => {
```

2022-06-09 20:15 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.tsx
> +          {(profileFields as unknown as IProfileFields[]).map(({ name, type, options }) =>
В коменте ниже есть подсказка по отдельному интерфейсу для описания полей, тогда эта конструкция с unknown будет не нужна.

2022-06-09 20:17 UTC, MatthewPattell commented on src/pages/user/overview/index.tsx
> +
К примеру:
```
interface IEntityField {
  name: string;
  type?: 'select' | 'text' | 'date'; // text by default
  options?: ISelectOptions;
}
```

2022-06-09 20:19 UTC, MatthewPattell commented on src/pages/user/edit-profile/index.tsx
> +          {(profileFields as unknown as IProfileFields[]).map(({ name, type, options }) =>
Плюс, по красоте можно создать супер компонент аля Fields в который можно вкидывать массивы [...profileFields, ...userFields] и этот компонент отрендерит нужные поля Field или Select или еще что, будет в дальнейшем 100%

2022-06-13 18:58 UTC, MatthewPattell requested changes

2022-06-13 18:58 UTC, MatthewPattell commented on src/pages/user/data.ts
> +  { name: 'username', type: 'text', title: i18n.t('users-page:username') },
type: 'text' вообще можно сделать по дефолту чтобы явно не указывать. Явно указывать будем все остальное

2022-06-13 18:58 UTC, MatthewPattell commented on src/pages/user/index.tsx
> +import UserHelper from '@store/entities/user';
UserEntity

2022-06-13 18:58 UTC, MatthewPattell commented on src/common/components/overview/index.tsx
> +import type { IEntityField } from '@components/fields';
давай сделаем эти два компонента дочерними для Overview (перенеси их в src/common/components/overview/...)

2022-06-14 06:29 UTC, MatthewPattell requested changes

2022-06-14 06:29 UTC, MatthewPattell commented on src/common/components/overview/fields/index.tsx
> +import type { FC } from 'react';
сорян, попутал, компонент Fields нужно положить в components/forms

2022-06-14 06:29 UTC, MatthewPattell commented on src/pages/user/data.ts
> +import i18n from '@common/services/localization';
common не стоит использовать.
import i18n from '@services/localization';

2022-06-14 06:29 UTC, MatthewPattell commented on src/pages/user/data.ts
> +const profileFields = [
Я думаю можно себя обезопасить и накинуть интерфейсы к полям

const profileFields: IField[] = [

2022-06-14 06:31 UTC, MatthewPattell requested changes

2022-06-14 06:31 UTC, MatthewPattell commented on src/common/components/overview/index.tsx
> +const Overview: FC<IOverview> = ({ data, title }) => (
jsdoc: Print entity fields

2022-06-14 06:47 UTC, MatthewPattell requested changes

2022-06-14 06:47 UTC, MatthewPattell commented on src/common/components/overview/index.tsx
> +import type { IField } from '../forms/fields';
алиас уже здесь

2022-06-14 06:47 UTC, MatthewPattell commented on src/pages/user/change-password/fields.ts
>  const fields = [
а здесь че не накинул IField[]

2022-06-14 07:08 UTC, MatthewPattell approved these changes

2022-06-14 07:09 UTC, merged