feat(identity-provider): create page
Lomray-Software/microservices-dashboard pull request #8
Opened 2022-06-17 15:16 UTC by olegatorlelik

NOT FINAL VERSION

2022-06-17 15:24 UTC, MatthewPattell requested changes
src/pages/user/identity-providers/styles.module.scss

пустой файл

2022-06-17 15:24 UTC, MatthewPattell commented on src/common/components/tabs/index.tsx
> +      shouldChildren?: boolean;
зачем этот флаг? Ты просто children не передавай и все

2022-06-17 15:24 UTC, MatthewPattell commented on src/pages/user/identity-providers/index.tsx
> +  id?: string;
userId

2022-06-17 15:24 UTC, MatthewPattell commented on src/store/endpoints/interfaces/common/query.ts
> +  userId?: string;
что это такое? убрать

2022-06-17 15:24 UTC, MatthewPattell commented on src/store/modules/pages/user/identity-providers.ts
> +        userId: id,
userId: id, находиться должен в where

where: {
 ...this.where,
userId,
}

2022-06-18 08:21 UTC, olegatorlelik commented on src/common/components/tabs/index.tsx
> +      shouldChildren?: boolean;
У меня написано так, что мы ребенка передаем в tabs а не в компоненты.

2022-06-18 11:42 UTC, MatthewPattell requested changes

2022-06-18 11:42 UTC, MatthewPattell commented on src/common/components/tabs/index.tsx
> +      shouldChildren?: boolean;
не понял

2022-06-18 11:42 UTC, MatthewPattell commented on src/common/components/tabs/index.tsx
> +      <div className={shouldChildren ? '' : styles.fullSize}>{Component}</div>
по сути здесь же можно просто сделать так:
```
{children}
 <div className={React.isValidElement(children) ? '' : styles.fullSize}>{Component}</div>
```

или 

React.Children.count(children)

2022-06-19 19:56 UTC, MatthewPattell requested changes
src/pages/user/identity-providers/styles.module.scss

пустой?

2022-06-19 19:56 UTC, MatthewPattell commented on src/pages/user/identity-providers/index.tsx
> +    ),
что это?

2022-06-19 20:14 UTC, olegatorlelik commented
NOT FINAL VERSION!!!

2022-06-20 10:43 UTC, MatthewPattell requested changes

2022-06-20 10:43 UTC, MatthewPattell commented on src/common/components/overview/index.tsx
> +          return <EntityFields key={fields.join('')} data={result} />;
до этого было лучше

2022-06-20 10:47 UTC, olegatorlelik commented on src/common/components/overview/index.tsx
> +          return <EntityFields key={fields.join('')} data={result} />;
Я переписал иначе, так как у нас есть вероятность что в result может лежать только один элемент а индекс подставить со значение к примеру 2. И это будет неверно. Поэтому я это поправил в комите выше.

2022-06-20 11:41 UTC, MatthewPattell commented on src/common/components/overview/index.tsx
> +          return <EntityFields key={fields.join('')} data={result} />;
массив объектов... странно его джойнить, это ж не массив строк..

2022-06-20 11:41 UTC, MatthewPattell commented on src/common/components/overview/index.tsx
> +          return <EntityFields key={fields.join('')} data={result} />;
Тогда лучше сделать явно так:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/10459911/174594214-6bd5f0be-ad79-4f38-bfcf-931621143859.png">

2022-06-20 16:19 UTC, MatthewPattell requested changes

2022-06-20 16:19 UTC, MatthewPattell commented on src/pages/user/identity-providers/index.tsx
> +        maxWidth: 50,
по идее если только maxWidth тоже должно работать

2022-06-20 16:19 UTC, MatthewPattell commented on src/store/modules/pages/user/identity-providers.ts
> +  public async removeIdentity(): Promise<void> {
```suggestion
  public async removeIdentity(provider: string, identifier: string): Promise<void> {
```

2022-06-20 16:19 UTC, MatthewPattell commented on src/store/modules/pages/user/identity-providers.ts
> +      },
```suggestion
      query: {
        where: {
          userId: this.userPageStore.user?.id,
          provider,
          identifier
        },
      },
```

2022-06-20 16:19 UTC, MatthewPattell commented on src/store/modules/pages/user/identity-providers.ts
> +    const { entities, deleted } = result;
удалить эту строку

2022-06-20 16:19 UTC, MatthewPattell commented on src/store/modules/pages/user/identity-providers.ts
> +    this.setIdentities(entities);
this.setIdentities(this.identityProvides.filter((identity) => identity.provider === provider && identity.identifier === identifier));

2022-06-20 16:19 UTC, MatthewPattell commented on src/pages/user/identity-providers/index.tsx
> +          <ButtonPrimary kind="secondary" onClick={removeIdentity}>
здесь нужно передавать конкретные данные

2022-06-20 17:55 UTC, MatthewPattell approved these changes

2022-06-20 17:55 UTC, merged